server:
  port: 8090
spring:
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 100MB

# 阿里云基本配置
aliyun:
  oss:
    ossEndPoint: oss-cn-xxx.aliyuncs.com    #地域节点地址
    http_path: https://xxx.oss-cn-xxx.aliyuncs.com/    #外网访问地址
    accessKeyId: xxx   #accessKeyId
    accessKeySecret: xxx #accessKeySecret
    filedir: image/ # 存储路径
    bucket_name: xxx   #oss控制中心创建的 bucket的名称